
exports.seed = function(knex) {

  return knex('residents3').del()
    .then(function () {
      return knex('residents3').insert([
      { 
        name: "Doris",
        photo: "https://erinwritesnow.files.wordpress.com/2017/01/cute-happy-older-lady.jpg",
        age: "87",
        height: "5'9\"",
        weight: "145 lbs",
        pcp: "Dr. Uppitomison",
        ambulatory: "yes",
        help_with_medications: "yes",
        other_impairments: "visual impairment",
        previous_career: "Seamstress",
        interests: "knitting, cats, card games, unsolved mysteries",
        pets: "one cat",
        living_preferences: "",
        semester: "Spring 2021",
        additional_notes: "I need help feeding my cat, Mittens. Please don't eat peanuts around me, I am terribly allergic."
      },
      { 
        name: "Ralph",
        photo: "https://previews.123rf.com/images/natakot/natakot1810/natakot181001281/110094284-happy-old-man-showing-thumbs-up-working-out-with-a-dumbbell.jpg",
        age: "75",
        height: "5'11\"",
        weight: "190 lbs",
        pcp: "Dr. Segura",
        ambulatory: "yes",
        help_with_medications: "no",
        other_impairments: "early stage memory loss",
        previous_career: "Small business owner",
        interests: "Weightlifting, billiards, NY stock exchange",
        pets: "none",
        living_preferences: "I like to wake up early and stay active.",
        semester: "Spring 2021",
        additional_notes: "Once a month, my 12-year-old grandson comes to stay with me. He's a good kid and is fine sleeping on the couch."
      },
      { 
        name: "",
        photo: "",
        age: "",
        height: "5'5\"",
        weight: "125 lbs",
        pcp: "Dr. Green",
        ambulatory: "no",
        help_with_medications: "yes",
        other_impairments: "multiple sclerosis",
        previous_career: "",
        interests: "",
        pets: "dog",
        living_preferences: "",
        semester: "Spring 2021",
        additional_notes: ""
      },
      { 
        name: "Sylvia",
        photo: "https://ak.picdn.net/shutterstock/videos/19998196/thumb/11.jpg",
        age: "78",
        height: "5'5\"",
        weight: "115 lbs",
        pcp: "Dr. Green",
        ambulatory: "yes",
        help_with_medications: "yes",
        other_impairments: "slight visual impairment",
        previous_career: "piano teacher",
        interests: "playing piano, taking care of my plants, playing with my cats, watching movies",
        pets: "two cats, Oscar and Ollie",
        living_preferences: "I like to keep the house clean and let in lots of natural light for the plants during the day.",
        semester: "Fall 2021",
        additional_notes: "I love to play piano and am happy to share my knowledge with students if they are interested."
      },
      { 
        name: "",
        photo: "",
        age: "82",
        height: "5'4\"",
        weight: "120 lbs",
        pcp: "Dr. Segura",
        ambulatory: "no",
        help_with_medications: "yes",
        other_impairments: "",
        previous_career: "Elementary School Teacher",
        interests: "",
        pets: "",
        living_preferences: "",
        semester: "Summer 2021",
        additional_notes: ""
      },
      { 
        name: "Alan",
        photo: "https://ak.picdn.net/shutterstock/videos/3078532/thumb/10.jpg",
        age: "76",
        height: "6'1\"",
        weight: "165 lbs",
        pcp: "Dr. Morgan",
        ambulatory: "yes",
        help_with_medications: "no",
        other_impairments: "minor visual impairment, respiratory disease",
        previous_career: "Session Musician",
        interests: "jazz, trumpet, cooking, keeing up with my granddaughters",
        pets: "none",
        living_preferences: "I like to keep humidifiers running all the times to help with my breathing",
        semester: "Summer 2021",
        additional_notes: "I like to keep up with my girls on FaceTime with the phone or iPad, but sometimes need help setting it up correctly"
      },
      { 
        name: "Jerry",
        photo: "",
        age: "80",
        height: "6'",
        weight: "220 lbs",
        pcp: "Dr. Fraser",
        ambulatory: "no",
        help_with_medications: "yes",
        other_impairments: "high blood pressure",
        previous_career: "Restaurant owner",
        interests: "cooking, football, baseball, card games",
        pets: "none",
        living_preferences: "",
        semester: "Fall 2021",
        additional_notes: "I am the world's best chef. I just need help carrying in the groceries!"
      }
    ])
  })
};
